spring.application.name=dbCrud

# Configurazione della connessione al database MySQL su Azure

spring.datasource.url=jdbc:mysql://enaip.mysql.database.azure.com:3306/scuola?useSSL=true&requireSSL=true&verifyServerCertificate=false

spring.datasource.username=myadminsql
spring.datasource.password=samerBakhit1
#spring.datasource.url=jdbc:mysql://localhost:3306/dbcrud
#spring.datasource.username=root
#spring.datasource.password=samerBakhit#1
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver




spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.jpa.properties.hibernate.format_sql=true

spring.jpa.open-in-view=false




spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.mode=HTML
spring.thymeleaf.encoding=UTF-8



